"""Agregando nuevos campos al modelo

Revision ID: 27d380c2904c
Revises: dedf1cf2441d
Create Date: 2025-02-04 22:55:41.394157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d380c2904c'
down_revision = 'dedf1cf2441d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superficie_util', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('superficie_total', sa.Float(), nullable=True))

    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('constructora', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propiedades', schema=None) as batch_op:
        batch_op.drop_column('constructora')
        batch_op.drop_column('fecha_entrega')

    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.drop_column('superficie_total')
        batch_op.drop_column('superficie_util')

    # ### end Alembic commands ###
