"""Sincronizando cambios manuales

Revision ID: 7f8bee995623
Revises: 
Create Date: 2025-02-03 22:29:24.566564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f8bee995623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.alter_column('gastos_comunes',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('estacionamientos',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('bodega',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_constraint('fk_propiedad_detalle', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_propiedad_detalle', 'propiedades', ['propiedad_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('bodega',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('estacionamientos',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('gastos_comunes',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
