"""Corrigiendo relación Categoria-Propiedad

Revision ID: 8ece7fb0cac0
Revises: 51ca6bd0477c
Create Date: 2025-02-03 23:29:34.057491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ece7fb0cac0'
down_revision = '51ca6bd0477c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_detalle', type_='foreignkey')
        batch_op.create_foreign_key(None, 'propiedades', ['propiedad_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_propiedades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_detalle', 'propiedades', ['propiedad_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
