"""Agregando tablas de regiones, ciudades y comunas

Revision ID: fd287b6a7031
Revises: 27d380c2904c
Create Date: 2025-02-06 00:28:29.169478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd287b6a7031'
down_revision = '27d380c2904c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunas')
    op.drop_table('ciudades')
    op.drop_table('regiones')
    # ### end Alembic commands ###
